# Data Structures

[Python 3 Tutorial](https://docs.python.org/3/tutorial/datastructures.html)

## Digression

What is an iterable?

https://stackoverflow.com/questions/9884132/what-exactly-are-pythons-iterator-iterable-and-iteration-protocols

An ITERABLE is:

* anything that can be looped over (i.e. you can loop over a string or file) or
* anything that can appear on the right-side of a for-loop:  `for x in iterable: ...` or
* anything you can call with `iter()` that will return an ITERATOR:  `iter(obj)` or
* an object that defines `__iter__` that returns a fresh ITERATOR, or it may have a `__getitem__` method suitable for indexed lookup.

An ITERATOR is an object:

* with state that remembers where it is during iteration,
* with a `__next__` method that:
    * returns the next value in the iteration
    * updates the state to point at the next value
    * signals when it is done by raising StopIteration
* and that is self-iterable (meaning that it has an `__iter__` method that returns `self`).

Notes:

* The `__next__` method in Python 3 is spelt `next` in Python 2, and
* The builtin function `next()` calls that method on the object passed to it.

In [1]:
sentence = 'classic text'    # an ITERABLE
                             # a str object that is immutable
                             # no state
                             # has a __getitem__() method 

In [2]:
iter_sentence = iter(sentence)    # an ITERATOR
                                  # has state (it starts by pointing at the "c" in "classic text"
                                  # has a next() method and an __iter__() method

In [3]:
next(iter_sentence)

'c'

In [4]:
next(iter_sentence)

'l'

In [5]:
next(iter_sentence)

'a'

In [6]:
next(iter_sentence)

's'

## More on Lists

### append

`list.append(x)`

Add an item to the end of the list. Equivalent to `a[len(a):] = [x]`.

In [7]:
a = [1, 2, 3]

In [8]:
a.append(4)

In [9]:
a

[1, 2, 3, 4]

### extend

`list.extend(iterable)`

Extend the list by appending all the items from the iterable. Equivalent to `a[len(a):] = iterable`.

In [10]:
b = [11, 22]

In [11]:
b.extend(a)

In [12]:
b

[11, 22, 1, 2, 3, 4]

### insert

`list.insert(i, x)`

Insert an item at a given position. The first argument is the index of the element before which to insert, so `a.insert(0, x)` inserts at the front of the list, and `a.insert(len(a), x)` is equivalent to `a.append(x)`.

In [13]:
b

[11, 22, 1, 2, 3, 4]

In [14]:
b.insert(3, 1007)

In [15]:
b

[11, 22, 1, 1007, 2, 3, 4]

### remove

`list.remove(x)`

Remove the first item from the list whose value is x. It is an error if there is no such item.

In [16]:
b

[11, 22, 1, 1007, 2, 3, 4]

In [17]:
b.remove(1)

In [18]:
b

[11, 22, 1007, 2, 3, 4]

In [19]:
b.remove(7)

ValueError: list.remove(x): x not in list

### pop

`list.pop([i])`

Remove the item at the given position in the list, and return it. If no index is specified, `a.pop()` removes and returns the last item in the list. (The square brackets around the $i$ in the method signature denote that the parameter is optional, not that you should type square brackets at that position. You will see this notation frequently in the Python Library Reference.)

In [20]:
b

[11, 22, 1007, 2, 3, 4]

In [21]:
b.pop(2)

1007

In [22]:
b

[11, 22, 2, 3, 4]

### clear

`list.clear()`

Remove all items from the list. Equivalent to `del a[:]`.


In [23]:
a

[1, 2, 3, 4]

In [24]:
b

[11, 22, 2, 3, 4]

In [25]:
c = a         # copy by assignment 
d = b.copy()  # shallow copy

In [26]:
c

[1, 2, 3, 4]

In [27]:
c.clear()

In [28]:
c

[]

In [29]:
a

[]

In [30]:
d

[11, 22, 2, 3, 4]

In [31]:
d.clear()

In [32]:
d

[]

In [33]:
b

[11, 22, 2, 3, 4]

### index

`list.index(x[, start[, end]])`

Return zero-based index in the list of the first item whose value is $x$. Raises a ValueError if there is no such item.

The optional arguments start and end are interpreted as in the slice notation and are used to limit the search to a particular subsequence of the list. The returned index is computed relative to the beginning of the full sequence rather than the start argument.

In [34]:
b

[11, 22, 2, 3, 4]

In [35]:
b.index(3)

3

### count

`list.count(x)`

Return the number of times $x$ appears in the list.


In [36]:
b

[11, 22, 2, 3, 4]

In [37]:
b = b + b
b

[11, 22, 2, 3, 4, 11, 22, 2, 3, 4]

In [38]:
b.count(11)

2

### sort

`list.sort(key=None, reverse=False)`

Sort the items of the list in place (the arguments can be used for sort customization, see `sorted()` for their explanation).


In [39]:
b

[11, 22, 2, 3, 4, 11, 22, 2, 3, 4]

In [40]:
b.sort()

In [41]:
b

[2, 2, 3, 3, 4, 4, 11, 11, 22, 22]

In [42]:
b.sort(reverse=True)

In [43]:
b

[22, 22, 11, 11, 4, 4, 3, 3, 2, 2]

### reverse

`list.reverse()`

Reverse the elements of the list in place.


In [44]:
b

[22, 22, 11, 11, 4, 4, 3, 3, 2, 2]

In [45]:
b.reverse()

In [46]:
b

[2, 2, 3, 3, 4, 4, 11, 11, 22, 22]

### copy

`list.copy()`

Return a shallow copy of the list. Equivalent to `a[:]`.

[reference](https://docs.python.org/3/library/copy.html)

In [47]:
base_eg = [3, 4, 6, [7., 5.]]

In [48]:
base_assignment = base_eg    # assignment
base_assignment

[3, 4, 6, [7.0, 5.0]]

In [49]:
base_assignment[1] = 0.4
base_assignment

[3, 0.4, 6, [7.0, 5.0]]

In [50]:
base_eg

[3, 0.4, 6, [7.0, 5.0]]

Note the copy by assignment. It is pointing to the same location. When you change the "copy", you changed the origin.

Assignment statements in Python do not copy objects, they create bindings between a target and an object. For collections that are mutable or contain mutable items, a copy is sometimes needed so one can change one copy without changing the other. 

In [51]:
base_shallow_copy = base_eg.copy()    # shallow copy
base_shallow_copy

[3, 0.4, 6, [7.0, 5.0]]

In [52]:
base_shallow_copy[1] = 3991
base_shallow_copy

[3, 3991, 6, [7.0, 5.0]]

In [53]:
base_eg

[3, 0.4, 6, [7.0, 5.0]]

Note that due to shallow copy, the original data was not affected. There is still a problem though. The problem arise, when you change the list.

In [54]:
base_shallow_copy[3][0] = 999.99
base_shallow_copy

[3, 3991, 6, [999.99, 5.0]]

In [55]:
base_eg

[3, 0.4, 6, [999.99, 5.0]]

In this situation, we will need to perform deepcopy

In [56]:
from copy import deepcopy

In [57]:
base_deep_copy = deepcopy(base_eg)    # deep copy
base_deep_copy

[3, 0.4, 6, [999.99, 5.0]]

In [58]:
base_deep_copy[1] = 1e44
base_deep_copy

[3, 1e+44, 6, [999.99, 5.0]]

In [59]:
base_eg

[3, 0.4, 6, [999.99, 5.0]]

In [60]:
base_deep_copy[3][1] = 2.4e43
base_deep_copy

[3, 1e+44, 6, [999.99, 2.4e+43]]

In [61]:
base_eg

[3, 0.4, 6, [999.99, 5.0]]

### Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use `append()`. To retrieve an item from the top of the stack, use `pop()` without an explicit index. For example:

In [62]:
lifo = list(range(2, 6))
lifo

[2, 3, 4, 5]

In [63]:
lifo.append(3.14)
lifo

[2, 3, 4, 5, 3.14]

In [64]:
lifo.pop()
lifo

[2, 3, 4, 5]

### Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use `collections.deque` which was designed to have fast appends and pops from both ends. For example:

In [65]:
from collections import deque

In [66]:
name_list = ['John', 'Michael', 'Bruce', 'Abby']

In [67]:
fifo = deque(name_list)
fifo

deque(['John', 'Michael', 'Bruce', 'Abby'])

In [68]:
fifo.popleft()

'John'

In [69]:
fifo

deque(['Michael', 'Bruce', 'Abby'])

### List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

Three ways to create a list of cube

In [70]:
# Method 1: Normal Loop

cubes = []
for n in range(0, 10):
    cubes.append(n * n * n)
cubes

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [71]:
# Method 2: Lambda

cubes = list(map(lambda x:x*x*x, range(10)))
cubes

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [72]:
# Method 3: List comprehension

cubes = [x*x*x for x in range(0, 10)]
cubes

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

`for` loop versue `list comprehension`

In [73]:
combs = []
class_1 = ['Jimmy', 'Audrey', 'Ono']

for stud_1 in class_1:
    for stud_2 in class_1:
        if stud_1 != stud_2:
            combs.append((stud_1, stud_2))

combs

[('Jimmy', 'Audrey'),
 ('Jimmy', 'Ono'),
 ('Audrey', 'Jimmy'),
 ('Audrey', 'Ono'),
 ('Ono', 'Jimmy'),
 ('Ono', 'Audrey')]

In [74]:
[(stud_1, stud_2) for stud_1 in class_1 for stud_2 in class_1 if stud_1 != stud_2]

[('Jimmy', 'Audrey'),
 ('Jimmy', 'Ono'),
 ('Audrey', 'Jimmy'),
 ('Audrey', 'Ono'),
 ('Ono', 'Jimmy'),
 ('Ono', 'Audrey')]

More examples of list comprehension

In [75]:
x_train = list(range(-4, 8, 2))
x_train

[-4, -2, 0, 2, 4, 6]

Doubling the number

In [76]:
[x**2 for x in x_train]

[16, 4, 0, 4, 16, 36]

Applying absolute to all the elements

In [77]:
[abs(x) for x in x_train]

[4, 2, 0, 2, 4, 6]

In [78]:
y_train = ['American Bulldog  ', 'Berger Picard,', 'Bullmastiff', 'Collie', 'Harrier']
y_train

['American Bulldog  ', 'Berger Picard,', 'Bullmastiff', 'Collie', 'Harrier']

In [79]:
[y.strip() for y in y_train]

['American Bulldog', 'Berger Picard,', 'Bullmastiff', 'Collie', 'Harrier']

In [80]:
[y.strip(",") for y in y_train]

['American Bulldog  ', 'Berger Picard', 'Bullmastiff', 'Collie', 'Harrier']

In [81]:
[y.strip().strip(",").upper() for y in y_train]

['AMERICAN BULLDOG', 'BERGER PICARD', 'BULLMASTIFF', 'COLLIE', 'HARRIER']

In [82]:
list_in_list = [['Javanese', 'Egyptian Mau', 'Persian'], 
                ['Sphynx', 'Scottish Fold', 'Manx'], 
                ['Korat', 'Burmese', 'Bengal']]

In [83]:
unpacked = []
for num in list_in_list:
    for n in num:
        unpacked.append(n)

unpacked    

['Javanese',
 'Egyptian Mau',
 'Persian',
 'Sphynx',
 'Scottish Fold',
 'Manx',
 'Korat',
 'Burmese',
 'Bengal']

In [84]:
[n for num in list_in_list for n in num]

['Javanese',
 'Egyptian Mau',
 'Persian',
 'Sphynx',
 'Scottish Fold',
 'Manx',
 'Korat',
 'Burmese',
 'Bengal']

### Nested List Comprehensions

In [85]:
matrix = [[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12]]

In [86]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [87]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In the real world, you should prefer built-in functions to complex flow statements. The `zip()` function would do a great job for this use case:

In [88]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

For more on 

* [Unpacking Argument Lists](https://docs.python.org/3/tutorial/controlflow.html#tut-unpacking-arguments)

* [zip](https://docs.python.org/3/library/functions.html#zip)

* [Built-in Functions](https://docs.python.org/3/library/functions.html)

## The del statement

There is a way to remove an item from a list given its index instead of its value: the `del` statement. This differs from the `pop()` method which returns a value. The `del` statement can also be used to remove slices from a list or clear the entire list (which we did earlier by assignment of an empty list to the slice). For example:

In [89]:
cats_list = ['Javanese', 'Egyptian Mau', 'Persian', 'Sphynx', 'Scottish Fold', 'Manx']
cats_list

['Javanese', 'Egyptian Mau', 'Persian', 'Sphynx', 'Scottish Fold', 'Manx']

In [90]:
del cats_list[2]

In [91]:
cats_list

['Javanese', 'Egyptian Mau', 'Sphynx', 'Scottish Fold', 'Manx']

In [92]:
del cats_list[2:]

In [93]:
cats_list

['Javanese', 'Egyptian Mau']

In [94]:
del cats_list

In [95]:
cats_list

NameError: name 'cats_list' is not defined

***

## Tuples and Sequences

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are two examples of `sequence` data types (see [Sequence Types — list, tuple, range](https://docs.python.org/3/library/stdtypes.html#typesseq)). Since Python is an evolving language, other sequence data types may be added. There is also another standard sequence data type: the `tuple`.

A tuple consists of a number of values separated by commas, for instance:


In [96]:
t = 12.54, 33.33, 'Blood Moon!'

In [97]:
type(t)

tuple

In [98]:
t

(12.54, 33.33, 'Blood Moon!')

In [99]:
t[0]

12.54

In [100]:
# Tuples may be nested:

u = t, (1, 2, 3, 4, 5)

In [101]:
u

((12.54, 33.33, 'Blood Moon!'), (1, 2, 3, 4, 5))

In [102]:
# Tuples are immutable:

t[0] = 2012

TypeError: 'tuple' object does not support item assignment

In [103]:
# but they can contain mutable objects:

v = ([2,3,4],[6,7,8])

In [104]:
v

([2, 3, 4], [6, 7, 8])

In [105]:
type(v)

tuple

As you see, on output tuples are always enclosed in parentheses, so that nested tuples are interpreted correctly; they may be input with or without surrounding parentheses, although often parentheses are necessary anyway (if the tuple is part of a larger expression). It is not possible to assign to the individual items of a tuple, however it is possible to create tuples which contain mutable objects, such as lists.

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are [immutable](https://docs.python.org/3/glossary.html#term-immutable), and usually contain a heterogeneous sequence of elements that are accessed via unpacking (see later in this section) or indexing (or even by attribute in the case of [namedtuples](https://docs.python.org/3/library/collections.html#collections.namedtuple)). Lists are [mutable](https://docs.python.org/3/glossary.html#term-mutable), and their elements are usually homogeneous and are accessed by iterating over the list.

A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective. For example:

In [106]:
empty_t = ()

In [107]:
type(empty_t)

tuple

In [108]:
failed_single_t = (12.66)

In [109]:
type(failed_single_t)

float

In [110]:
single_t = (12.66,)    # <-- note trailing comma

In [111]:
type(single_t)    

tuple

The statement `t = 12.54, 33.33, 'Blood Moon!'` is an example of tuple packing: the values `12.54, 33.33, 'Blood Moon!'` are packed together in a tuple. The reverse operation is also possible:

In [112]:
x, y, z = t

In [113]:
x

12.54

This is called, appropriately enough, `sequence unpacking` and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

## Sets

Python also includes a data type for `sets`. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the `set()` function can be used to create sets. Note: to create an empty set you have to use `set()`, not `{}`; the latter creates an empty dictionary, a data structure that we discuss in the next section.

In [114]:
shopping_list = ['MacBook', 'ChromeBook Pixel', 'Nexus 5X', 'Nokia N1', 'Nexus 5X',
                  'Nexus 5X', 'MacBook', 'ChromeBook Pixel']
print(shopping_list)
print(len(shopping_list))

['MacBook', 'ChromeBook Pixel', 'Nexus 5X', 'Nokia N1', 'Nexus 5X', 'Nexus 5X', 'MacBook', 'ChromeBook Pixel']
8


In [116]:
shopping_list = {'MacBook', 'ChromeBook Pixel', 'Nexus 5X', 'Nokia N1', 'Nexus 5X',
                  'Nexus 5X', 'MacBook', 'ChromeBook Pixel'}
print(shopping_list)
print(len(shopping_list))

{'Nokia N1', 'MacBook', 'Nexus 5X', 'ChromeBook Pixel'}
4


In [117]:
'MacBook' in shopping_list

True

In [118]:
'Macbook' in shopping_list

False

In [119]:
x = set('qweertaaqwepo')
y = set('arwertqwrwerq')

In [120]:
x    # unique letters in x

{'a', 'e', 'o', 'p', 'q', 'r', 't', 'w'}

In [121]:
y    # unique letters in y

{'a', 'e', 'q', 'r', 't', 'w'}

In [122]:
x - y    # letters in x but not in y

{'o', 'p'}

In [123]:
x | y    # letters in x or y or both

{'a', 'e', 'o', 'p', 'q', 'r', 't', 'w'}

In [124]:
x & y    # letters in both x and y

{'a', 'e', 'q', 'r', 't', 'w'}

In [125]:
x ^ y    # letters in x or y but not both

{'o', 'p'}

Similarly to list comprehensions, set comprehensions are also supported.

## Dictionaries

Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by `keys`, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like `append()` and `extend()`.

It is best to think of a dictionary as an unordered set of `key: value` pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: `{}`. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with `del`. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing `list(d.keys())` on a dictionary returns a list of all the keys used in the dictionary, in arbitrary order (if you want it sorted, just use `sorted(d.keys())` instead). To check whether a single key is in the dictionary, use the `in` keyword.

In [126]:
customer_info = {'Jim': 1550, 'Bob': 1010}

In [127]:
type(customer_info)

dict

In [128]:
customer_info['Lisa'] = 2345

In [129]:
customer_info

{'Bob': 1010, 'Jim': 1550, 'Lisa': 2345}

In [130]:
del customer_info['Jim']

In [131]:
customer_info

{'Bob': 1010, 'Lisa': 2345}

In [132]:
customer_info['Liz'] = 1240

In [133]:
customer_info

{'Bob': 1010, 'Lisa': 2345, 'Liz': 1240}

In [134]:
list(customer_info.keys())

['Bob', 'Lisa', 'Liz']

In [135]:
'Liz' in customer_info

True

In [136]:
'Jim' in customer_info

False

The `dict()` constructor builds dictionaries directly from sequences of key-value pairs:

In [137]:
dict([('Johnson', 1008), ('El', 1009), ('Baye', 1011)])

{'Baye': 1011, 'El': 1009, 'Johnson': 1008}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [138]:
{x: x**3 for x in range(10, 16, 2)}

{10: 1000, 12: 1728, 14: 2744}

When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [139]:
dict(Johnson=1008, El=1009, Baye=1011)

{'Baye': 1011, 'El': 1009, 'Johnson': 1008}

## Looping Techniques

When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the `items()` method.

In [140]:
scale = {'small': 'S', 'large': 'L'}

In [141]:
for key, value in scale.items():
    print(key, value)

small S
large L


To loop over two or more sequences at the same time, the entries can be paired with the `zip()` function.

In [142]:
AAPL = [172.5, 170.1, 160.5]
IBM = [80.5, 83.52, 84.53]

In [143]:
for stk1, stk2 in zip(AAPL, IBM):
    print('AAPL={0} IBM={1}'.format(stk1, stk2))

AAPL=172.5 IBM=80.5
AAPL=170.1 IBM=83.52
AAPL=160.5 IBM=84.53


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the `reversed()` function.

In [144]:
for i in reversed(AAPL):
    print(i)

160.5
170.1
172.5


To loop over a sequence in sorted order, use the `sorted()` function which returns a new sorted list while leaving the source unaltered.

In [145]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

In [146]:
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [147]:
import math

In [148]:
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]

In [149]:
filtered_data = []

In [150]:
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

In [151]:
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

## More on Conditions

The conditions used in `while` and `if` statements can contain any operators, not just comparisons.

The comparison operators `in` and `not in` check whether a value occurs (does not occur) in a sequence. The operators `is` and `is not` compare whether two objects are really the same object; this only matters for mutable objects like lists. All comparison operators have the same priority, which is lower than that of all numerical operators.

Comparisons can be chained. For example, `a < b == c` tests whether `a` is less than `b` and moreover `b` equals `c`.

Comparisons may be combined using the Boolean operators `and` and `or`, and the outcome of a comparison (or of any other Boolean expression) may be negated with `not`. These have lower priorities than comparison operators; between them, `not` has the highest priority and `or` the lowest, so that `A and not B or C` is equivalent to `(A and (not B)) or C`. As always, parentheses can be used to express the desired composition.

The Boolean operators `and` and `or` are so-called `short-circuit` operators: their arguments are evaluated from left to right, and evaluation stops as soon as the outcome is determined. For example, if `A` and `C` are true but `B` is false, `A and B and C` does not evaluate the expression `C`. When used as a general value and not as a Boolean, the return value of a short-circuit operator is the last evaluated argument.

It is possible to assign the result of a comparison or other Boolean expression to a variable. For example,

In [152]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'

In [153]:
non_null = string1 or string2 or string3

In [154]:
non_null

'Trondheim'

## Comparing Sequences and Other Types

Sequence objects may be compared to other objects with the same sequence type. The comparison uses `lexicographical` ordering: 

* first the first two items are compared, and 
    * if they differ this determines the outcome of the comparison; 
    * if they are equal, the next two items are compared, and so on, 
    * until either sequence is exhausted. 
* If two items to be compared are themselves sequences of the same type, the lexicographical comparison is carried out recursively. 
* If all items of two sequences compare equal, the sequences are considered equal. 
* If one sequence is an initial sub-sequence of the other, the shorter sequence is the smaller (lesser) one. 

Lexicographical ordering for strings uses the Unicode code point number to order individual characters. Some examples of comparisons between sequences of the same type:

In [155]:
(1, 2, 3) < (1, 2, 4)

True

In [156]:
[1, 2, 3] < [1, 2, 4]

True

In [157]:
'ABC' < 'C' < 'Pascal' < 'Python'

True

In [158]:
(1, 2, 3, 4) < (1, 2, 4)

True

In [159]:
(1, 2) < (1, 2, -1)

True

In [160]:
(1, 2, 3) == (1.0, 2.0, 3.0)

True

In [161]:
(1, 2, ('aa', 'ab')) < (1, 2, ('abc', 'a'), 4)

True

Note that comparing objects of different types with `<` or `>` is legal provided that the objects have appropriate comparison methods. For example, mixed numeric types are compared according to their numeric value, so 0 equals 0.0, etc. Otherwise, rather than providing an arbitrary ordering, the interpreter will raise a `TypeError` exception.

***

# References:

* [Python Tutorial](https://docs.python.org/3.6/tutorial/index.html)
* [Geeks for Geeks](https://www.geeksforgeeks.org/python/)
* [Python for Econometrics](https://www.kevinsheppard.com/Python_for_Econometrics)
* [Python Course](https://www.kevinsheppard.com/Python_Course)


***